
ALTER TABLE bridge_table 
ALTER COLUMN CHANNEL_DIM_SKEY TYPE BIGINT,
ALTER COLUMN FOLIO_DIM_SKEY TYPE BIGINT,
ALTER COLUMN KARVY_REF_NO TYPE BIGINT,
ALTER COLUMN FOLIO_ID TYPE BIGINT,
ALTER COLUMN MF_SALES_TRXN_FACT_SKEY TYPE BIGINT;
