CREATE TABLE IF NOT EXISTS bridge_table(MyUnknownColumn INT NOT NULL, 
                                        CHANNEL_DIM_SKEY BIGINT NOT NULL, 
                                        FOLIO_DIM_SKEY BIGINT NOT NULL, 
                                        KARVY_REF_NO BIGINT NOT NULL, 
                                        FOLIO_ID BIGINT NOT NULL,
                                        SCHEME_CODE VARCHAR NOT NULL,
                                        SCHEME_PLAN VARCHAR NOT NULL, 
                                        TRXN_PIN_CODE INT NULL, 
                                        TRXN_CAT VARCHAR NULL, 
                                        TRXN_TYPE VARCHAR NOT NULL,
                                        TXN_SUB_TYPE VARCHAR NULL, 
                                        INSTRUMENT_TYPE VARCHAR NULL, 
                                        INSTRUMENT_BANK VARCHAR NULL, 
                                        LOAD_PERCENTAGE FLOAT NULL,
                                        TRXN_DATE DATE NULL, 
                                        TXN_PROCESSING_DATE DATE NULL, 
                                        TRXN_BATCH_CLOSE_DATE DATE NULL,
                                        TRXN_STATUS VARCHAR NULL, 
                                        NO_OF_UNITS FLOAT NULL, 
                                        PRICE_PER_UNIT FLOAT NULL, 
                                        APPLICABLE_NAV_DATE DATE NULL,
                                        APPLICABLE_NAV FLOAT NULL, 
                                        APPLICABLE_POP FLOAT NULL, 
                                        GROSS_AMOUNT FLOAT NULL, 
                                        REMARKS VARCHAR NULL,
                                        RECORD_VALID_FLAG VARCHAR NULL, 
                                        INVESTOR_LOCATION INT NULL, 
                                        PIN_CODE_DIM_SKEY INT NULL,
                                        ONLINE_OFFLINE_FLAG VARCHAR NULL, 
                                        INVESTOR_TYPE VARCHAR NULL, 
                                        TRXN_PROCESS_FLAG VARCHAR NULL,
                                        TRXN_CLASSIFICATION VARCHAR NULL, 
                                        MF_SALES_TRXN_FACT_SKEY BIGINT NULL, 
                                        CHANNEL_ID VARCHAR NULL, 
                                        RIA_CODE VARCHAR NULL, 
                                        is_excluded BOOLEAN NULL,
                                        is_reversal BOOLEAN NULL,
                                        PRIMARY KEY(MyUnknownColumn)
                                        );
